### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by 10616413** [FruitbatM/roast-hive#10]
I will have a look at this, using your trial runner one as template - hope that's OK Marina

**Comment by FruitbatM** [comment]
Absolutely. You don't need to ask.

**Comment by 10616413** [comment]
thanks
[User Stories_FR_1.0.xlsx](https://github.com/FruitbatM/roast-hive/files/11357609/User.Stories_FR_1.0.xlsx)

**Comment by 10616413** [comment]
started - not sure if everything is in there but lets meet and go through it
